2023-09-13 11:55:39,119 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('new/post_list.html'), <traceback object at 0x0000029438FA3540>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: new/post_list.html
2023-09-13 11:55:39,121 - ERROR - "GET /news/ HTTP/1.1" 500 87853 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
